browserify = require 'browserify'
watchify = require 'watchify'
mkdirp = require 'mkdirp'
path = require 'path'
{openSync, writeSync, closeSync} = require 'fs'
uglify = require 'uglify-js'

class BrowserifyInstance
  constructor: (@data) ->
    options =
      debug: !@data.main.production
    for own k,v of watchify.args
      options[k] = v
    for own k,v of @data.instanceOptions
      options[k] = v
    if @data.bundleOptions
      # Backward compatibility with old configs
      for own k,v of @data.bundleOptions
        options[k] = v

    @__w = browserify "./#{@data.entry}", options
    @__w = watchify(@__w) if @data.main.watching

    for transform in @data.transforms
      @__w.transform(transform)

    @data.onBrowserifyLoad?.apply this, [@__w]

    if @data.main.watching
      @__w.on 'update', @handleUpdate
      @handleUpdate()

    null

  handleUpdate: (fileContents, filePath, callback) =>
    @running = true
    @data.onBeforeBundle?.apply this, [@__w]

    @__w.bundle (error, js) =>
      if error or not js?
        if not @data.main.watching
          throw error

        console.error 'Browserify Error', error
        callback? error || true, fileContents, filePath
        return

      # Browserify > 5.0.0 gives us a buffer object, must convert it to string.
      js = js.toString()

      # Since the files run through browserify are not defined in
      # `brunchConfig.files.javascripts`, they are not picked up by the
      # installed optimizers.
      if @data.main.production
        minified = uglify.minify js, fromString: true
        js = minified.code

      # Likewise, we don't get folders generated by Brunch.
      outputFile = "#{@data.main.publicPath}/#{@data.compiledPath}"
      mkdirp.sync path.dirname(outputFile)
      fd = openSync outputFile, 'w+'
      writeSync fd, js
      closeSync fd

      @running = false
      @data.onAfterBundle?.apply this, arguments
      @data.main.__autoReloadServer?.sendMessage 'page'
      callback? error, fileContents, filePath

module.exports = {
  BrowserifyInstance
}
